version: 0.1

phases:
  pre_build:
    commands:
      - npm install
      - npm test
  build:
    commands:
      #- npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - images/*
    - css/*
    - dist/bundle.js
